"""change type of weight field

Revision ID: 1b5a50294815
Revises: 044c2e934224
Create Date: 2023-06-18 22:09:10.576578

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1b5a50294815'
down_revision = '044c2e934224'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'weight')
    op.add_column('products', sa.Column('weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'weight')
    op.add_column('products', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
