"""added date of creation field for product

Revision ID: 1efbdcdbe008
Revises: 4305cc8da8f8
Create Date: 2023-06-08 20:10:07.829073

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1efbdcdbe008'
down_revision = '4305cc8da8f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('date_of_creation', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'date_of_creation')
    # ### end Alembic commands ###
