"""added tables 3

Revision ID: 2850b10ebb06
Revises: 215fab16c953
Create Date: 2023-05-30 18:32:46.608078

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2850b10ebb06'
down_revision = '215fab16c953'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('brand', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=False),
    sa.Column('material_color', sa.Integer(), nullable=False),
    sa.Column('cutting', sa.Integer(), nullable=True),
    sa.Column('stone', sa.Integer(), nullable=True),
    sa.Column('weaving', sa.Integer(), nullable=True),
    sa.Column('style', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['cutting'], ['cuttings.id'], ),
    sa.ForeignKeyConstraint(['material'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['material_color'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['stone'], ['stones.id'], ),
    sa.ForeignKeyConstraint(['style'], ['styles.id'], ),
    sa.ForeignKeyConstraint(['weaving'], ['weavings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('role_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'name')
    op.drop_table('products')
    # ### end Alembic commands ###
