"""DataBase Update

Revision ID: 39448e8ac62d
Revises: 388cf4205592
Create Date: 2023-05-26 00:42:30.755683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39448e8ac62d'
down_revision = '388cf4205592'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
