"""added tables 4

Revision ID: 4305cc8da8f8
Revises: 2850b10ebb06
Create Date: 2023-05-30 18:34:40.257396

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4305cc8da8f8'
down_revision = '2850b10ebb06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('products_id', sa.ARRAY(sa.Integer()), nullable=False),
                    sa.Column('status', sa.Text(), nullable=False),
                    sa.Column('address', sa.Text(), nullable=False),
                    sa.Column('order_date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('role_permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
